version: '3'
services:

  mongodb:
    image: mongo:3.6
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - ./data/db:/data/db
    networks:
      - mynetwork
    restart: always

# network
networks:
  mynetwork:
    driver: bridge